# Generated by Django 2.2.16 on 2020-10-18 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('duration', models.IntegerField()),
                ('city', models.CharField(choices=[('WAR', 'Warsaw'), ('KRK', 'Krakow'), ('GDA', 'Gdansk')], max_length=3)),
                ('activity_type', models.CharField(choices=[('CLS', 'Classic'), ('CRZ', 'Crazy')], max_length=3)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('order', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlanActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(choices=[(1, '1:00 AM'), (2, '2:00 AM'), (3, '3:00 AM'), (4, '4:00 AM'), (5, '5:00 AM'), (6, '6:00 AM'), (7, '7:00 AM'), (8, '8:00 AM'), (9, '9:00 AM'), (10, '10:00 AM'), (11, '11:00 AM'), (12, '12:00 AM'), (13, '1:00 PM'), (14, '2:00 PM'), (15, '3:00 PM'), (16, '4:00 PM'), (17, '5:00 PM'), (18, '6:00 PM'), (19, '7:00 PM'), (20, '8:00 PM'), (21, '9:00 PM'), (22, '10:00 PM'), (23, '11:00 PM'), (24, '12:00 AM')])),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_breaks_app.Activities')),
                ('travel_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_breaks_app.TravelPlan')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('week_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='city_breaks_app.WeekDay')),
            ],
        ),
        migrations.AddField(
            model_name='travelplan',
            name='activities',
            field=models.ManyToManyField(through='city_breaks_app.TravelPlanActivities', to='city_breaks_app.Activities'),
        ),
        migrations.AddField(
            model_name='travelplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
