# Generated by Django 2.2.16 on 2020-10-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_breaks_app', '0003_auto_20201018_2026'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='travelplan',
            name='A User can only have one Travel Plan with a same name',
        ),
    ]
